### ISSUE TITLE
Panel shortcode has empty <p> tags

### ISSUE THREAD

**Issue by juliotaylor** [bigspring/monolith#285] opened 2015-03-02 15:35 UTC
The `panel` shortcode outputs empty `<p>` tags which is causing shit layout.

Temporarily hacked/fixed via wack SCSS that removed bottom padding on shortcode-generated panels.

**Comment by jrgmartin** [comment] 2015-04-10 15:52
This is partially fixed.  I have removed the apply_filters call around the buttons shortcode.

The issue is that we need to run apply_filters for any shortcodes that have opening and closing tags otherwise any nested shortcodes will not run and will be displayed as text.  We do know that any shortcodes that don't have an opening and closing tag should never need to run apply_filters.

**Closed** 2016-02-12 15:57 UTC
Labels: bug, needs review
